substitutions:
  plug_name: sonoff_4ch_pro_01

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${plug_name}_button_1"
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "${plug_name}_button_2"
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "${plug_name}_button_3"
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "${plug_name}_button_4"
  - platform: status
    name: "${plug_name}_status"

switch:
  - platform: gpio
    name: "${plug_name}_relay_1"
    pin: GPIO12
  - platform: gpio
    name: "${plug_name}_relay_2"
    pin: GPIO5
  - platform: gpio
    name: "${plug_name}_relay_3"
    pin: GPIO4
  - platform: gpio
    name: "${plug_name}_relay_4"
    pin: GPIO15

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "${plug_name}_blue_led"
    output: blue_led

sensor:
# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: "${plug_name}_uptime"
